seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      dir: /mnt/scratch
      name: prelim_tests
      project: mri_clinical_tasks
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: 1
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: gpu
  strategy: ddp
  sync_batchnorm: false
  precision: 16
  enable_model_summary: true
  num_sanity_val_steps: 1
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: False
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
model:
  video_model: mvit
  pretrained: true
  video_model_depth: 50
  checkpoint_path: path_to_checkpoint_here
  multi_view_strategy: single_model
  proj_dim: 512
  proj_layers: 1
  dropout: 0.1
  mode: linear
  output_classes: 1
  multi_instance: false
  print_attention_maps: false
data:
  data_dir: /mnt/datastore/acdc_labelled_sax
  period: 110
  max_length: 96
  task: acdc
  frames: 16
  batch_size: 16
  mean: 0.0
  sd: 1.0
  crop_size: 224
  debug: false
  cpus: 5
  subsample_frames: true
  percentage: 1.0
data:
  class_path: data.data_modules.ACDC_Data_Module
  init_args:
    data_dir: /mnt/datastore/acdc_labelled_sax
    period: 110
    max_length: 96
    task: acdc
    frames: 16
    batch_size: 16
    mean: 0.0
    sd: 1.0
    crop_size: 224
    debug: false
    cpus: 5
    subsample_frames: true
    percentage: 1.0
optimizer:
  lr: 0.001
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.01
  amsgrad: false
lr_scheduler:
  step_size: null
  gamma: 0.1
  last_epoch: -1
  verbose: false
checkpoint_callback:
  dirpath: null
  filename: null
  monitor: null
  verbose: false
  save_last: null
  save_top_k: 1
  save_weights_only: false
  mode: min
  auto_insert_metric_name: true
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: 100
  save_on_train_epoch_end: null
rich_progressbar:
  refresh_rate: 10
  leave: false
  theme:
    description: black
    progress_bar: '#6206E0'
    progress_bar_finished: '#6206E0'
    progress_bar_pulse: '#6206E0'
    batch_progress: black
    time: black
    processing_speed: grey70
    metrics: black
  console_kwargs: null
ckpt_path: null
verbose: true